Update python-tests.yml

diff --git a/.github/workflows/python-tests.yml b/.github/workflows/python-tests.yml
--- a/.github/workflows/python-tests.yml
+++ b/.github/workflows/python-tests.yml
@@ -45,57 +45,65 @@ jobs:
 
   test:
     runs-on: ubuntu-latest
-    needs: download-history
+    outputs:
+      test-result: ${{ steps.run-tests.outputs.test-result }}
     steps:
-      - name: Install Selenium
-        run: pip install selenium
-      - name: Checkout repository
-        uses: actions/checkout@v3
-      - name: setup python
-        uses: actions/setup-python@v4
-        with:
-          python-version: "3.12"
-      - name: Install Chrome
-        run: sudo apt-get install google-chrome-stable
-      - name: install dependencies
-        run: pip install -r requirements.txt
-      - name: Download all workflow run artifact
-        uses: actions/download-artifact@v3
-      - name: Cleanup old artifacts
-        run: |
-          rm -rf allure-results/*
-      - name: Run tests
-        run: pytest tests/test_title_city.py --alluredir=allure-results
-        continue-on-error: true
-      - name: Store allure results
-        uses: actions/upload-artifact@v3
-        with:
-          name: allure-results
-          path: allure-results
-          retention-days: 1
+    - name: Install Selenium
+      run: pip install selenium
+    - name: Checkout repository
+      uses: actions/checkout@v3
+    - name: Setup Python
+      uses: actions/setup-python@v4
+      with:
+        python-version: "3.12"
+    - name: Install Chrome
+      run: sudo apt-get install google-chrome-stable
+    - name: Install dependencies
+      run: pip install -r requirements.txt
+    - name: Download all workflow run artifact
+      uses: actions/download-artifact@v3
+    - name: Cleanup old artifacts
+      run: |
+        rm -rf allure-results/*
+    - name: Run tests
+      id: run-tests
+      run: |
+        pytest tests/test_title_city.py --alluredir=allure-results
+        if [ $? -eq 0 ]; then
+          echo "test-result=success" >> $GITHUB_OUTPUT
+        else
+          echo "test-result=failure" >> $GITHUB_OUTPUT
+        fi
+      continue-on-error: true
+    - name: Store allure results
+      uses: actions/upload-artifact@v3
+      with:
+        name: allure-results
+        path: allure-results
+        retention-days: 1
 
   generate-report:
     runs-on: ubuntu-latest
     needs: test
     name: Generate report
     steps:
-      - uses: actions/setup-java@v3
-        with:
-          distribution: 'microsoft'
-          java-version: '17'
-      - run: |
-          sudo wget https://github.com/allure-framework/allure2/releases/download/2.23.1/allure-2.23.1.tgz
-          sudo tar -zxvf allure-2.23.1.tgz -C /opt/
-          sudo ln -s /opt/allure-2.23.1/bin/allure /usr/bin/allure
-      - name: Download all workflow run artifact
-        uses: actions/download-artifact@v3
-      - run: allure generate -c allure-results -o _site
-      - name: Store generated report
-        uses: actions/upload-artifact@v3
-        with:
-          name: _site
-          path: _site
-          retention-days: 1
+    - uses: actions/setup-java@v3
+      with:
+        distribution: 'microsoft'
+        java-version: '17'
+    - run: |
+        sudo wget https://github.com/allure-framework/allure2/releases/download/2.23.1/allure-2.23.1.tgz
+        sudo tar -zxvf allure-2.23.1.tgz -C /opt/
+        sudo ln -s /opt/allure-2.23.1/bin/allure /usr/bin/allure
+    - name: Download all workflow run artifact
+      uses: actions/download-artifact@v3
+    - run: allure generate -c allure-results -o _site
+    - name: Store generated report
+      uses: actions/upload-artifact@v3
+      with:
+        name: _site
+        path: _site
+        retention-days: 1
 
   publish-report:
     runs-on: ubuntu-latest
@@ -114,9 +122,9 @@ jobs:
         curl --location 'https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage' \
         --header 'Content-Type: application/json' \
         --data '{"chat_id":5030902696,"text": "Tests FAILED. Report https://nikita159821.github.io/Anrex/"}'
-    - name: Send Telegram message
-      if: needs.test.outputs.test-result == 'success'
-      run: |
-        curl --location 'https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage' \
-        --header 'Content-Type: application/json' \
-        --data '{"chat_id":5030902696,"text": "Tests PASSED. Report https://nikita159821.github.io/Anrex/"}'
+        - name: Send Telegram message
+        if: needs.test.outputs.test-result == 'success'
+        run: |
+          curl --location 'https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage' \
+          --header 'Content-Type: application/json' \
+          --data '{"chat_id":5030902696,"text": "Tests PASSED. Report https://nikita159821.github.io/Anrex/"}'
